### ISSUE TITLE
Creating a book from strings (?)

### ISSUE THREAD

**Issue by kzorin52** [Overrided/Fb2.Document#2]
Хотел кое-что спросить

**Comment by Overrided** [comment]
Hi there @kzorin52 
Glad you're interested in this library.
If you want to ask questions - I suppose ask here.
THIS is the place where code-related stuff happens.

Cheers

**Comment by kzorin52** [comment]
Hi! Can you please supplement the documentation by adding an example of **creating** a book from strings?

**Comment by Overrided** [comment]
I'm not 100% sure I got you right on ***creating book from a strings*** part. 
If you mean to load `fb2` file content into `Fb2Document` as a string - it's already there, I suggest you take a look at this [part of readme](https://github.com/Overrided/Fb2.Document#loading-file-as-a-string). 

You have to read your `fb2` file as a string and then call `Load` on `Fb2Document` instance passing file content. 
Also I advise to take a closer look at [Fb2Document.Load(string content)](https://github.com/Overrided/Fb2.Document/blob/7224d33178b99a3da3f03eb895a518eb862df277/Fb2.Document/Fb2Document.cs#L194) to clarify implementation details.

Hope this answers your question,
Cheers

**Comment by kzorin52** [comment]
No, I have a string "test", and I want to create book with text "test"

**Comment by Overrided** [comment]
Ok, I think I see what you are tying to do.
There is no automated way to create book with contents **YET** - those API's are being designed and will be added to some next version of a library eventually.
So far you can create a book - by creating tree structure manually, accordingly to `fb2` [standard](http://www.fictionbook.org/).
You need to point out what actually that "test" string is - is it `Title` element, or part of a `Annotation` element, or just text in some sub-child of a `BookBody`.
I think closest example of manual `Fb2Document` creation is in [IntegrationTests](https://github.com/Overrided/Fb2.Document/blob/7224d33178b99a3da3f03eb895a518eb862df277/Fb2.Document.Tests/IntegrationTests.cs#L65). This test generates simple document for integrity checks (document is not fully valid tho).

**Comment by kzorin52** [comment]
thanks

**Comment by Overrided** [comment]
Closing this issue due to no further activity.

**Comment by Overrided** [comment]
@kzorin52 if you are still interested, latest lib version has new API's for editing - check out readme for details.
